version: "3"

services:

  server:
    image: nginx:1.23.0
    container_name: server
    ports:
      - 4000:80
    links:
      - frontend:frontend
      - backend:backend
    volumes:
      - ./server/nginx.conf:/etc/nginx/nginx.conf
      - images:/usr/share/nginx/images:ro
    depends_on:
      - database
      - backend
      - frontend

  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    image: frontend
    container_name: frontend
    depends_on:
      - backend
    volumes:
      - ./frontend/src:/app/src
    expose:
      - '3000'
    env_file:
      - app.env

  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    image: backend
    restart: always
    container_name: backend
    depends_on:
      - database
    volumes:
      - images:/app/static/images
    expose:
      - '8000'
    env_file:
      - app.env

  database:
    # plarform for M1
    # platform: linux/x86_64
    image: mysql:8.0
    restart: always
    container_name: database
    volumes:
      - data:/var/lib/mysql
    expose:
      - '3306'
    env_file:
      - app.env

  adminer:
    image: adminer:4.8.1
    container_name: adminer
    ports:
      - '8080:8080'
    depends_on:
      - database
    environment:
      ADMINER_DEFAULT_SERVER: database

volumes:
  data: null
  images: null
